### ISSUE TITLE
Disk Catalog PDF Doc Improvement

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#440] opened 2024-10-15 05:12 UTC
I would like to raise an issue (enhancement) to improve the documentation for the project specifically in the Disk Catalog PDF document. This is primarily since I have put some time into this already, and think it can be greatly improved.

What is the Issue
* Firstly it is a bit incomplete, i.e. not all disks are described, 
* A lot of files and or descriptions are missing descriptions
* Contains duplicate file information, which makes it harder to maintain this document

Sources for Information
* The "d_*" directories that actually contain a list of the files
* The individual readme files in the "d_*"  directories actually contain a lot more information about the files than the PDF document, this is a big source of information
* The "hd_*.txt" files that contain definitions of what is copied onto the disk

Improvements
* Add sections for disks not already described, primary the standalone disks, e.g. d_games
* Create new section(s) which describes common files (e.g. Sound Files, Test Files, SIMH, etc) that are copied to multiple disks
* Remove the duplicate files from the main OS disk listings, and replace with pointers to the Common File sections.
* Copy disk and file descriptions from the individual readme files

Any comments, on how this could be improved. I will attach a sample showing where it is up to.

Mark.

[RomWBW Disk Catalog.pdf](https://github.com/user-attachments/files/17373026/RomWBW.Disk.Catalog.pdf)

**Comment by wwarthen** [comment] 2024-10-15 17:42
I strongly concur with the sentiment that the RomWBW disk catalog needs substantial improvement.  There have been multiple prior attempts to clean this up.  Sadly, none of them have "stuck".

From my point of view, the biggest issue is finding a way to keep the catalog up to date.  Improving the content of the catalog is probably just work.  Finding a process that makes maintenance of the catalog easier and more foolproof.

I also wish to solicit thoughts and ideas.  Improving the disk catalog would greatly enhance RomWBW.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-18 12:11
@wwarthen You also made a comment in the document itself:

```
**NOTE:** This document has become somewhat out-of-date.  I apologize
for this.  It is very difficult to maintain due to the volume of
disk content updates and the way that files are dynamically merged
into disk images during the build process.
```

One of the primary changes I have made is to break up the content of the disk catalog into various sections, which are referenced , thus there should only be ONE place where a file is defined. e.g. "FDISK80.COM" appears once, previously it appeared 5 times. Thus : 

This should hopefully improve the maintainability of the document

Th only downside of this is that the grouping of files in the document follows the underlying structure of where the file appears in the build structure. When reading the document (as a user it is a little arbitrary) e.g. Sections 3.3 and 3.4 specifically. 

I have attached a new PDF which show the current state,

[RomWBW Disk Catalog.pdf](https://github.com/user-attachments/files/17435160/RomWBW.Disk.Catalog.pdf)

**Comment by wwarthen** [comment] 2024-10-19 14:04
@kiwisincebirth,

Your work on the Disk Catalog looks really good Mark.  I like the organization and this would be much easier to maintain.  Perhaps a bit harder for a user to find what they want for a specific disk, but the current organization was not very maintainable and so was not very useful.

Thanks!  Wayne

**Comment by wwarthen** [comment] 2024-10-19 14:23
@kiwisincebirth,

Here are the answers to your questions about the disk content at the end of the document:

>In NZ-COM the Submit CPM22 is copied to U0. ALL OTHER CPM22 files are copied to U15 Is
this correct, why is this different? Is there a technical readon. d_cpm22/u0/SUBMIT.COM 0:

It is required to be in user 0 to facilitate the auto submit at startup mechanism.

>I have noticed ZPM3 distro includes CPM3LDR.SYS and CPM3LDR.COM. These disks already
include the correct ZPMLDR.SYS COM files which boots the OS Not shure why both are
included, are they included/needed for a specific purpose. Should we remove CPM3LDR.SYS
and CPM3LDR.COM from ZPM disk distributions. change to *_zpm3.txt

There have been some issues with the ZPM variants in the past.  I think I have fixed all the issues, but I'm not 100% sure.  The CPM3 versions were there as a failsafe.  Perhaps OK to remove now.

>Why are we including sample music files on FLOPPY disk images. Surely these dont need to
be here. On smaller media devices space is important Noting None of the Test programs are
beeing included, and some music files are already commented (assume for space) on larger
distro i.e. ZPM3.

I agree.  Probably never gave it much thought.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-19 14:27
Hi Wayne, thank for the feedback. I'll submit some Pr,s and raise any further questions on this issue.

**Comment by kiwisincebirth** [comment] 2024-10-19 14:30
Ps. Please review the first paragraph under section 5.2, I think there is room to delete several duplicate files from the build?

**Comment by wwarthen** [comment] 2024-10-19 18:41
Hi @kiwisincebirth,

With respect to 5.2:

>d_zpm3/u15 - Includes a copy of all the files from the CPM3/u0 folder The documentation
states this files, stating they come from CPM3. Ideally the CPM3 files in the d_zpm3/u15
(duplicates) should be deleted and the d_zpm.txt fle should copy these files.

Yes, definitely.  This should have been done long ago when I did the original dedup effort.  I will take care of this myself because I want to review the files included there.

>The /Source Apps folder has some off the appications directly in the Apps folder ideally they
should be in sub folders, one per app, most but not all are.

Yes, definitely.  Originally, all of the Apps were comingled directly in the Apps folder.  At some point, I realized that was not a good long-term solution and started using sub-folders.  I have never gone back and moved all the other apps to sub-folders, but I should.  Feel free to pursue this or I can can look at it in the next few days.

>And a couple of applcation are directly in the source folder, event though they are just a Binary
Applicaton. TastyBasic is one that comes to mind Although I may be wrong, isnt this also
distributed to ROM as an app but still might be better modev to apps folder

I agree, but I need to review this.  I think these apps (including TastyBasic) are ROM apps.  They may have some references into the HBIOS and may have dependencies on the hardware configuration.  This does not mean they shouldn't be moved to a better location, but I need look at what is going on there.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-19 22:40
> With respect to 5.2:

With resect to 5.2 I will leave this to you to look at for the moment. I have addressed the other items already in PR

**Comment by kiwisincebirth** [comment] 2024-10-19 23:59
@wwarthen  RE ZPM3

> Yes, definitely. This should have been done long ago when I did the original dedup effort. I will take care of this myself because I want to review the files included there.

I would take a look at GENCPM (cpm3 utility) with all its associated files. I don't believe it is functional in (ZPM3) its current form, as it is missing a lot of critical SPR files. However there are a couple of remnants of it. The main GENCPM.COM is in U15, and `../ZPM3/gencpm.dat 0:` is copied to U0. This should probably been cleaned up ; or completed and made to work.

**Comment by wwarthen** [comment] 2024-10-20 00:29
> @wwarthen RE ZPM3
> 
> > Yes, definitely. This should have been done long ago when I did the original dedup effort. I will take care of this myself because I want to review the files included there.
> 
> I would take a look at GENCPM (cpm3 utility) with all its associated files. I don't believe it is functional in (ZPM3) its current form, as it is missing a lot of critical SPR files. However there are a couple of remnants of it. The main GENCPM.COM is in U15, and `../ZPM3/gencpm.dat 0:` is copied to U0. This should probably been cleaned up ; or completed and made to work.

Hmmm... I just ran GENCPM on the vanilla ZPM3 drive and it worked.  The resultant CPM3.SYS worked.  Is it failing for you?

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-20 01:07
> Hmmm... I just ran GENCPM on the vanilla ZPM3 drive and it worked. The resultant CPM3.SYS worked. Is it failing for you?

No you are right, I have been looking at this too long. Will commit shortly. Suggestion would be place GENCPM.COM in U0 for consistency with CPM3. IMHO.

**Comment by wwarthen** [comment] 2024-10-21 23:07
I believe commit 0113852 addresses most of the remaining items:

- The CP/M 3 files that were duplicated in the ZPM3 disk contents have been removed and replaced with references to those files in the disk creation scripts.
- The applications that were found in the main Applications folder have been relocated to individual folders to be consistent with other applications.

There are a couple items that I have chosen to defer for now:

- The location of GENCPM.COM in ZPM3 is still in user area 15.  Moving it to user area 0 would be consistent with CP/M 3, but would be inconsistent with the ZCPR standard of putting applications in user area 15.  I don't want to move one application of many to user area 0.
- The location of ROM applications is a bit inconsistent.  TastyBasic is in a folder under the main Source folder.  Other ROM applications such as GAME are imbedded in the HBIOS folder.  This should be corrected, but needs to be a larger effort due to possible dependencies between these ROM applications and specific HBIOS configurations.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-22 05:58
@wwarthen - Changes look good

Here are some more questions, potential small fixes. 
* ZCNFG.COM and the associated CFG file that goes with it. There are 3 of these in the source
repository, (NZCOM,ZPM3,BP). It may be a good candidate to move to a Common/Z3/U15 folder since it appears to be the
same version (should be ?) across these distributions, since I beleive the ar
* Is there an opportunity to consolidate the files in Common/UTILS/ and move contents into Common/All/ ? Both folders are included on all HD images. the difference is that FD images only contain /All , but not /UTILS. Is this potentially an oversight?

**Comment by wwarthen** [comment] 2024-10-22 19:09
Hi @kiwisincebirth,

Good questions, as always.

> * ZCNFG.COM and the associated CFG file that goes with it. There are 3 of these in the source
>   repository, (NZCOM,ZPM3,BP). It may be a good candidate to move to a Common/Z3/U15 folder since it appears to be the
>   same version (or should be ?) across these distributions.

Yup, needs to be fixed.  This is a ZSDOS utility (does not require ZCPR3), so the files belong in Common/Z.  The .com goes to u15 and the .cfg goes to U14.  You are welcome to work on this.

This question reminded me that there is a related (and bigger) problem.  Notice that the files in Source/ZSDOS/Distribution and Source/Images/d_zsdos/u0 are largely duplicated.  I think that Source/ZSDOS/Distribution needs to go away.  Then, like the CPM22 files, the ZSDOS files can be added to the other locations (ZPM and BP) as appropriate.  I think I need to work on this though.  The files need to be reviewed one by one.

> * Is there an opportunity to consolidate the files in Common/UTILS/ and move contents into Common/All/ ? Both folders are included on all HD images. the difference is that FD images only contain /All , but not /UTILS. Is this potentially an oversight? UTILS contains only 3 files, and there look very general e.g. LS.COM

The problem is that the files in UTILS will not fit on some of the floppy images.  It is not terribly intuitive, but UTILS was created as a way to differentiate between core files and supplemental files.  Core files should go on the floppy images. Supplemental files (UTIL) are not included on floppy images to conserve space.  I suspect that the categorization of the files has become corrupted over time, but I think there is still an issue with the files fitting on some of the floppy images.  However, I believe that the UTIL files probably will fit on **some** of the floppy images.  I left it off of all of them to be consistent.  You are free to look into that if you want and include the UTILS on those floppy images where they fit.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-22 20:57
> Notice that the files in Source/ZSDOS/Distribution and Source/Images/d_zsdos/u0 are largely duplicated. I think that Source/ZSDOS/Distribution needs to go away. 

I had noticed this. I separately found the zsdos distribution (zip) files. as a suggestion you could just include the original ZIP files, removing the unzipped contents.

Note: I have installed a Z3Plus and learning about it, while it has its pros and cons it is well documented, thus i think it would make a worthy disk image, I was considering contributing it as a disk image thus the interest in files, etc.  Question: the readme file ( in images/d_nzcom ) folder, is this a complete list of how you customised NZ-COM ?

And last question - documentation on Dos65 and BP have mostly been omitted from you official pdf documentation, is there a reason for this? Dos65 looks very fringe with a very small audience BP looks more generalised and part of your build. IMHO they both deserve a mention in the main User Guide, and BP probably should be added to disk catalog.

**Comment by wwarthen** [comment] 2024-10-22 22:15
> > Notice that the files in Source/ZSDOS/Distribution and Source/Images/d_zsdos/u0 are largely duplicated. I think that Source/ZSDOS/Distribution needs to go away.
> 
> I had noticed this. I separately found the zsdos distribution (zip) files. as a suggestion you could just include the original ZIP files, removing the unzipped contents.

As it stands, ZSDOS is the only OS where I included the distribution files.  I am not inclined to include the distribution files for all the OSes because the repository is already out of control.  The ZSDOS distribution is easily located on the web, so I am inclined to remove it and make it consistent with the other OSes.  It probably does make sense to make sure that a link to the distribution of each OS is found somewhere in the documentation.  I think I included some, but not sure I did it consistently.

> And last question - documentation on Dos65 and BP have mostly been omitted from you official pdf documentation, is there a reason for this? Dos65 looks very fringe with a very small audience BP looks more generalised and part of your build. IMHO they both deserve a mention in the main User Guide, and BP probably should be added to disk catalog.

Well, those are both **very** experimental and definitely not ready for general use.

- DOS65 is for a 6502 CPU on a specific platform from Dan Werner.  It operates as a secondary CPU, so I included a boot disk as a convenience for Dan and his users.  I think I need to clarify this in the ReadMe in that directory.  I will also add a link to the project website which is the best way to get more information and documentation.

- BPBIOS is very much a work-in-progress and highly experimental at this point.  I should add a ReadMe file for this disk image stating that.  There is some documentation for BPBIOS, but I have not yet included it because it is not ready for users.  I'm not sure it ever will be.  It would be a major effort to finish it off and the source for large pieces of it are lost.  Unfortunate.

Thanks, Wayne

**Comment by kiwisincebirth** [comment] 2024-10-23 01:40
> The problem is that the files in UTILS will not fit on some of the floppy images. It is not terribly intuitive, but UTILS was created as a way to differentiate between core files and supplemental files. Core files should go on the floppy images. Supplemental files (UTIL) are not included on floppy images to conserve space. I suspect that the categorization of the files has become corrupted over time, 

I agree with this. Why is LS.COM a Utility and TDLBASIC.COM a Core file. I think a seperate task is to revaluate this and seperate the files appropriately. 

> but I think there is still an issue with the files fitting on some of the floppy images. 

You are correct The files don't all fit, the big problem is fd_ZPM3, however I have a solution, which I will commit. But fd_ZPM3 is an issue. I compared it to hd_ZPM3, and space clearly is a bit issue. 

The slightly bigger issue here is that each FD definition has selectively commented, or removed /Binary/Apps obviously to make things fit, but there is NO consistency. Maybe a better cleanup would be to define a consistent cut down list of /Binary/Apps for use on a floppy disk. It probably wouldn't be hard since you just take a minimal definition

The problem here is that this is all work.

**Comment by kiwisincebirth** [comment] 2024-10-23 03:05
> ZCNFG.COM and the associated CFG file that goes with it. There are 3 of these in the source repository, (NZCOM,ZPM3,BP). It may be a good candidate to move to a Common/Z3/U15 folder since it appears to be the same version (or should be ?) across these distributions.

> Yup, needs to be fixed. This is a ZSDOS utility (does not require ZCPR3), so the files belong in Common/Z. The .com goes to u15 and the .cfg goes to U14. You are welcome to work on this.

Fixed in next commit.  Note Additionally I found some other binary duplicates between NZCOM and ZPM, which I move into Common/Z3
* EDITNDR.COM, SAVENDR.COM
* SDZ.COM
* ZEX.COM, ZEX.CFG

There were a couple of same (named) files, with different versions. Pimarily, i have captured this in the Documentation, but potentially the never file could be shared.
* SALIAS.COM v1.5 (NZ) and v1.6 (ZPM3)

**Comment by kiwisincebirth** [comment] 2024-10-23 12:26
FYI : Since last PR have also found COPY.COM and associated CFG file should be consolidated to Common/Z folder(s)

**Comment by wwarthen** [comment] 2024-10-23 20:18
Hi @kiwisincebirth,

>There were a couple of same (named) files, with different versions, i have captured this in the Documentation, but I think these are valid. However for SALIAS.COM (screen alias editor), there are 2 versions. v1.5 (NZCOM) and v1.6 (ZPM3). Maybe the Newer version could be adopted and shared in both OS's ?

Yes.  In the past, when I detected this situation, I looked for the most recent version available in the various CP/M Internet repositories and consolidated on the most recent version I could find.  I see an SALIAS16B is available.  I will go ahead and take care of switching to that version and making it shared.

>And related ALIAS.COM (which creates a new alias - interactive command line) is present in ZPM3, but not in NZCOM - it seems like such a general purpose tool, which would work equally in both OS's, (A brief test showed it did work) ?

Yes, ALIAS predates SALIAS.  I think that the creator of NZCOM intentionally used SALIAS as a replacement for ALIAS.  Regardless, for now, I will move ALIAS to Common/Z3 so it will be put consistently in bth NZCOM and ZPM3 disk images.  It can always be removed from there.

Thanks, Wayne

**Closed** 2024-10-25 07:54 UTC
Labels: enhancement
