### ISSUE TITLE
RC2014 pageable ROM/64k ram support?

### ISSUE THREAD

**Issue by deelowe** [wwarthen/RomWBW#7] opened 2018-02-06 04:21 UTC
Would it be feasible to support the rc2014 pro kit which comes with the pageable rom/ram modules?

Example: https://www.tindie.com/products/Semachthemonkey/rc2014-pro-homebrew-z80-computer-kit/

**Comment by wwarthen** [comment] 2018-02-06 18:08
Unfortunately, RomWBW is fundamentally a bank switching BIOS.  By design, it requires a minimum of 3 32K banks of RAM and 2 32K banks of ROM.  There really is no simple way of factoring out the need for the minimal number of RAM/ROM banks, thus the requirement for the 512KB RAM/ROM module.

This has been discussed offline in the past with Spencer.  He is considering various options for an "official" module that will provide support for RomWBW.

I am going to close this enhancement request for now, but if I have misunderstood what you are suggesting, please let me know!

Thanks,

Wayne

**Closed by wwarthen** 2018-02-06 18:08 UTC
Labels: enhancement
