### ISSUE TITLE
HBIOS function always returns an error

### ISSUE THREAD

**Issue by Pellatonian** [wwarthen/RomWBW#105] opened 2020-03-20 14:33 UTC
BF-DIOMEDIA  returns an unexplained error.

TSTPT taken just before and after the HBIOS call for unit 3 (IDE secondary):

+++++ TSTPT: @D9B5[0064:1803:3001:FC1E:FDF4] 
+++++ TSTPT: @D9B9[FEA0:C800:0000:19FD:FDF4] 

Initially I PANICed on receiving this error. After removing the PANIC the media detection for all units went OK.

The disk config is:

MD: UNITS=2 ROMDISK=384KB RAMDISK=384KB
IDE: IO=0x10 MODE=RC
IDE0: 8-BIT LBA BLOCKS=0x0003C200 SIZE=120MB
IDE1: NO MEDIA
SD: MODE=SC OPR=0x0C CNTR=0xCA TRDR=0xCB DEVICES=1
SD0: SDSC NAME=SA01G BLOCKS=0x001E6000 SIZE=972MB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            38400,8,N,1
Char 1      ASCI1:      RS-232            38400,8,N,1
Disk 0      MD1:        RAM Disk          384KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA
Disk 2      IDE0:       Hard Disk         120MB,LBA
Disk 3      IDE1:       Hard Disk         --
Disk 4      SD0:        SD Card           972MB,LBA

By the way,
Thanks for a great product!!
Steve Williams.

**Comment by wwarthen** [comment] 2020-03-20 15:29
Thanks for reporting this Steve.

Can you send me a little more information:

1. RomWBW version?
2. Hardware platform and boards installed?
3. Location of the PANIC call you removed?

Thanks,

Wayne

**Comment by Pellatonian** [comment] 2020-03-20 15:43
Hi Wayne,

1. The RomWBW version is Pre.34. 
2. It was on an SC126 with CF (single) interface and SD interface.
3. Sorry, I didn’t make it clear: the code is in my own BIOS, the PANIC I removed was my own code. 

The TSTPTs were taken immediately before and after the RST 1 calls so they reflect the parameters and results.

Best regards,
Steve.

**Comment by wwarthen** [comment] 2020-03-20 16:32
Ah, this helps a lot.

It looks like you are making the BF_DIOMEDIA call with a unit value of 0x03.  It looks like unit 0x03 has no media installed.  So, the call returns with a non-zero value indicating an error occurred.  The status return value of 0xFE is defined in the IDE driver as IDE_STNOMEDIA, which seems correct.

So... I guess my next question is what seems wrong here?  :-)

Thanks,

Wayne

**Comment by Pellatonian** [comment] 2020-03-20 16:52
OK,

The architecture document defines a media ID of 0 (MID_NONE) as an interface with no media installed. This is what I tested for in reg e.

I had wrongly interpreted a non-zero status in reg a as an error, either in the parameters of the call to HBIOS or in it’s own internal processing. Since the second CF interface is a valid one, just doesn’t happen to have a card installed, I didn’t interpret inquiring about the media as an error. 

Further, the error code of 0FEh was unexpected - the document says to expect the value of 1 on error, so I assumed the call was returning garbage.

Not a big problem. Thanks for looking at it.

Best regards,
Steve.

PS: Document correction. The function for DIOMED on page 16 is incorrectly stated as $13 in the Input box.

**Comment by wwarthen** [comment] 2020-03-20 16:59
Thanks Steve.  All valid points.I definitely see the confusion caused by the error return vs. MID_NONE.  I will correct the documentation on all of this.

Thanks!

Wayne

**Comment by wwarthen** [comment] 2020-03-20 17:47
OK, just checked in the updates.  I am going to close this issue, but let me know of any further problems.

Thanks!

Wayne

**Closed by wwarthen** 2020-03-20 17:47 UTC
