### ISSUE TITLE
BIOS 3.2.0 Disk probe is very slow on RCbus if the bus is not floating at 78

### ISSUE THREAD

**Issue by EtchedPixels** [wwarthen/RomWBW#343] opened 2023-04-21 17:28 UTC
One of my systems floats at B8 or sometimes F8 depending how it feels (not the giant one as it happens). The boot hangs during the IDE probe for a long time as it seems to confuse the check for a second device on the CF.

You possibly want to try writing AA and 55 to one of the LBA registers to see if the device is there ? Fuzix does the Linux trick of selecting the device then checking it can put AA and 55 into LBA0 and read them back before waiting and that seems to work in this case.

**Comment by wwarthen** [comment] 2023-04-21 17:36
I will definitely look at this right away.  Thanks @EtchedPixels.

**Comment by wwarthen** [comment] 2023-04-22 00:39
I believe this is resolved in commit e43a939.

You can test from the dev branch source or the latest Development Snapshot on the [Releases Page](https://github.com/wwarthen/RomWBW/releases).  I am going to leave this issue open for a few days to ensure it is fixed and there are no side-effects from the solution.

Thanks,

Wayne

**Comment by EtchedPixels** [comment] 2023-04-22 10:52
That did the trick

Thanks

**Comment by wwarthen** [comment] 2023-04-22 20:17
Thank you for taking the time to test this @EtchedPixels.

I think it is reasonable to close the issue at this point.

Thanks,

Wayne

**Closed by wwarthen** 2023-04-22 20:17 UTC

**Comment by wwarthen** [comment] 2023-04-24 02:20
So, this fix turned out to cause a small regression.  Spinning hard disks stopped being detected at power-up because they refuse to take register read/writes until they are ready (after spin up).  I have added a hack to handle this, but I'm not thrilled with it.  This is in commit ad3c533.

@EtchedPixels, it seems like Fuzix would have the same problem with spinning hard disks.  Have you tried them?

**Comment by wrljet** [comment] 2023-04-24 02:26
Wayne,

I continue to be amazed by the good work put into this project!!

Bill

**Comment by wwarthen** [comment] 2023-04-24 17:37
Ah, yes, if RomWBW or boot firmware is in front of Fuzix, then it would not be an issue.  This is not a priority, just a curiosity for me, so don't waste too much time researching it..  I went on a Google search mission yesterday, but was not able to find a good treatment on the ideal way to do IDE probing at power-up.
