### ISSUE TITLE
N8 (4314) and PPIDE

### ISSUE THREAD

**Issue by AndriiKu** [wwarthen/RomWBW#188] opened 2021-02-03 08:09 UTC
Hi Wayne,

Can't make PPIDE work on N8 (4314).

I add to my config file

PPIDEENABLE .SET TRUE ; PPIDE: ENABLE PARALLEL PORT IDE DISK DRIVER (PPIDE.ASM)
PPIDE0A8BIT .SET TRUE ; PPIDE 0A (MASTER): 8 BIT XFER
PPIDE0B8BIT .SET TRUE ; PPIDE 0B (SLAVE): 8 BIT XFER
PPIDE0BASE .SET $80 ; PPIDE 1: PPI REGISTERS BASE ADR

I'm use some previous tested CF's with CF-IDE adapter, different tested ppi 8255. Double check all signal and pcb track.
also added wait states on IO and memory.
Without a result. The card is not determined at the start. Sometimes with different errors.
The question arose when I didn't find a file .\Doc\Testing Notes.txt
mention of the testing of the ppide. there's only this:

N8-2312 (X)
-------
- Test ASCI driver
- Test SD driver (CSIO mode)
- Test FD driver
- Test FDU app
- Test TMS driver (video & kbd)

Please say should PPIDE work on N8 with this BIOS ?

Thanks
Andrii

**Comment by b1ackmai1er** [comment] 2021-02-03 14:01
Hi Andrii, looking at the n8-2511_-_ jumper settings file indicated to me that the PPI port should actually be $84 as $80 is printer, Keyboard and Mouse.  Try that port address as PPI base.

Regards Phil.

**Comment by wwarthen** [comment] 2021-02-03 19:15
Hi Andrii,

I tried it on my N8 which is a 2511 and it worked.  The only change I made to the config file was to enable PPIDE:

```
PPIDEENABLE	.SET	TRUE
```

My boot up messages are shown below in case that helps.

This configuration is indeed not on my normal regression testing list because it is not common.  Most people prefer to use the SD Card slot.  With that said, the IDE port is fast and effective, so a very reasonable choice.

@b1ackmai1er The correct I/O port is $80.  The 8255 at $80 is for either an IDE device or "parallel expansion" such as a DSKY.  I know that parallel expansion is a confusing term.  The 8255 at $84 is specifically designed for printer+keyboard+mouse.

Thanks,

Wayne

```
RomWBW HBIOS v3.1.1-pre.40, 2021-02-03

N8 (tst) Z8S180-N @ 18.432MHz IO=0x40
0 MEM W/S, 2 I/O W/S, INT MODE 2, N8 MMU
512KB ROM, 512KB RAM

AY: IO=0x9C
ASCI0: IO=0x40 ASCI W/BRG MODE=38400,8,N,1
ASCI1: IO=0x41 ASCI W/BRG MODE=38400,8,N,1
DSRTC: MODE=STD IO=0x88 Sun 2020-10-11 10:15:48 CHARGE=ON
TMS: IO=0x98
PPK: IO=0x84
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
FD: IO=0x8C UNITS=2
PPIDE: IO=0x80
PPIDE0: LBA BLOCKS=0x00773800 SIZE=3815MB
PPIDE1: NO MEDIA
SD: MODE=CSIO OPR=0x88 CNTR=0x4A TRDR=0x4B DEVICES=1
SD0: SDHC NAME=SD16G BLOCKS=0x01DACC00 SIZE=15193MB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            38400,8,N,1
Char 1      ASCI1:      RS-232            38400,8,N,1
Char 2      TERM0:      Terminal          Video 0,ANSI
Disk 0      MD1:        RAM Disk          256KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA
Disk 2      FD0:        Floppy Disk       3.5",DS/HD,CHS
Disk 3      FD1:        Floppy Disk       3.5",DS/HD,CHS
Disk 4      PPIDE0:     CompactFlash      3815MB,LBA
Disk 5      PPIDE1:     Hard Disk         --
Disk 6      SD0:        SD Card           15193MB,LBA
Video 0     TMS0:       CRT               Text,40x24
Sound 0     SND0:       AY-3-8910         3+1 CHANNELS


N8 (tst) Boot Loader

Boot [H=Help]:
```

**Comment by AndriiKu** [comment] 2021-02-03 19:15
Hi Phil,
I've thought about it before. Pcb have 2 PPI. Left (U2 on sheet) and right (U7).
To U2 connect LPT Port (P38) - port A PPI (through 74LS07 - U1, U65E,F) and the younger half of port C (PC0-PC3) through 74LS06 - U8 and the eldest half port B (PB4-PB7), key and mouse (port B (pins 0-3) and eldest half port C (pins PC4-PC7).
So this port (left on board U2) is completely busy.
CS for U2 go from pin 14 U58 and om sheet have name /CS_PPI2.
To U7 connect to socket P31 (all 24 pin all prot of this PPI) also PA0-7, PB0-7 and PC0-2 and PC3-7( through 74LS14 - U63))
CS for U2 go from pin 15 U58 and om sheet have name /CS_PPI1.
What am I talking about?  ))
I checked all the options and the table of truth.
I think there are no hardware problems.
The keyboard works on 84 port and when access to 80 port lights up the LED on the adapter. But then nothing happens.

**Comment by AndriiKu** [comment] 2021-02-03 19:16
https://photos.google.com/photo/AF1QipOz-Hfzg5h58Htx8f3pqJtLGmjBDF8oFp850lAe

**Comment by AndriiKu** [comment] 2021-02-03 19:19
Hi Wayne,

Before I wrote, I tried all the options. 
What can you advise me?

BR 
Andrii

**Comment by AndriiKu** [comment] 2021-02-04 10:13
I'll try prerelease 3.1.1

There is hope to:.

- WBW: Updated IDE and PPIDE drivers to improve old CF Card compatibility

They write it off

BR
Adrii

**Comment by wwarthen** [comment] 2021-02-04 19:42
> I'll try prerelease 3.1.1

It is worth a try, but I will be surprised if it helps.  The compatibility issue was pretty minor and you have already tried multiple CF cards.

Can you reply with a copy of the system boot messages (similar to what I posted?).  This will help me understand the exact scenario.

Thanks,

Wayne

**Comment by AndriiKu** [comment] 2021-02-04 19:45
Photo of boot screen i posted 2 message before.
Thanks
Andrii

**Comment by wwarthen** [comment] 2021-02-04 19:55
> Photo of boot screen i posted 2 message before.

Sorry, I missed that.  However, I just get a 404 error when I click that link.

**Comment by wwarthen** [comment] 2021-02-04 19:58
One more thing you can do to provide more information.  Set the PPIDETRACE config variable to 3 in your config file.

```
PPIDETRACE	.SET	3
```

Try booting after implementing that setting and send the messages.

Thanks,

Wayne

**Comment by AndriiKu** [comment] 2021-02-04 20:41
With new revision

RomWBW HBIOS v3.1.1-pre.40, 2021-02-04

N8 Z8S180-N @ 18.432MHz IO=0x40
0 MEM W/S, 2 I/O W/S, INT MODE 2, MMU=N8
512KB ROM, 1024KB RAM

AY: IO=0x9C
ASCI0: IO=0x40 ASCI W/BRG MODE=38400,8,N,1
ASCI1: IO=0x41 ASCI W/BRG MODE=38400,8,N,1
DSRTC: MODE=STD IO=0x88 Thu 2021-02-04 22:43:08 CHARGE=ON
TMS: IO=0x98
PPK: IO=0x84
MD: UNITS=2 ROMDISK=384KB RAMDISK=768KB
FD: IO=0x8C UNITS=2
PPIDE: IO=0x80 00
PPIDE0: RESET FAKE
PPIDE0: SELUNIT
PPIDE0: PROBE E0 80 [80 E0 00 00 00 00 01]
PPIDE0: BUSY TIMEOUT [D0 E0 00 00 01 01 04]
PPIDE0: NO MEDIA [D0 E0 00 00 01 01 04]
PPIDE0: SELUNIT
PPIDE0: PROBE F0 00
PPIDE0: NO MEDIA [00 00 00 00 00 00 00]
PPIDE0: NO MEDIA
PPIDE1: NO MEDIA
SD: MODE=CSIO OPR=0x88 CNTR=0x4A TRDR=0x4B DEVICES=1
SD0: SDSC NAME=00000 BLOCKS=0x003A9800 SIZE=1875MB

*** Activating CRT Console ***

**Comment by AndriiKu** [comment] 2021-02-04 20:44
next time some other

RomWBW HBIOS v3.1.1-pre.40, 2021-02-04

N8 Z8S180-N @ 18.428MHz IO=0x40
0 MEM W/S, 2 I/O W/S, INT MODE 2, MMU=N8
512KB ROM, 1024KB RAM

AY: IO=0x9C
ASCI0: IO=0x40 ASCI W/BRG MODE=38400,8,N,1
ASCI1: IO=0x41 ASCI W/BRG MODE=38400,8,N,1
DSRTC: MODE=STD IO=0x88 Thu 2021-02-04 22:45:38 CHARGE=ON
TMS: IO=0x98
PPK: IO=0x84
MD: UNITS=2 ROMDISK=384KB RAMDISK=768KB
FD: IO=0x8C UNITS=2
PPIDE: IO=0x80 00
PPIDE0: RESET FAKE
PPIDE0: SELUNIT
PPIDE0: PROBE E0 80 [80 00 00 00 00 00 01] [50 00 00 00 01 01 01] 50 01 01 00 00
PPIDE0: SETFEAT E0 81 EF --> 50
PPIDE0: IDDEV E0 EC --> 50 GETBUF
PPIDE0: DRQ TIMEOUT [50 00 00 00 01 01 01]
PPIDE0: SELUNIT
PPIDE0: PROBE F0 50 [50 00 00 00 01 01 01] [50 00 00 00 01 01 01] 50 01 01 00 00
PPIDE0: SETFEAT F0 81 EF --> 50
PPIDE0: IDDEV F0 EC --> 50 GETBUF
PPIDE0: DRQ TIMEOUT [50 00 00 00 01 01 01]
PPIDE0: DRQ TIMEOUT
PPIDE1: DRQ TIMEOUT
SD: MODE=CSIO OPR=0x88 CNTR=0x4A TRDR=0x4B DEVICES=1
SD0: SDSC NAME=00000 BLOCKS=0x003A9800 SIZE=1875MB

*** Activating CRT Console ***

**Comment by AndriiKu** [comment] 2021-02-04 20:45
This with additional config


#include "cfg_n8.asm"
;
Z180_CLKDIV	.SET	1		; Z180: CHK DIV: 0=OSC/2, 1=OSC, 2=OSC*2
Z180_MEMWAIT	.SET	0		; Z180: MEMORY WAIT STATES (0-3)
Z180_IOWAIT	.SET	1		; Z180: I/O WAIT STATES TO ADD ABOVE 1 W/S BUILT-IN (0-3)
;
CRTACT		.SET	TRUE		; ACTIVATE CRT (VDU,CVDU,PROPIO,ETC) AT STARTUP
;
SDMODE		.SET	SDMODE_CSIO	; SD: ENABLE SD CARD DISK DRIVER (SD.ASM)
RAMSIZE		.SET	1024		; SIZE OF RAM IN KB (MUST MATCH YOUR HARDWARE!!!)

PPIDEENABLE	.SET	TRUE		; PPIDE: ENABLE PARALLEL PORT IDE DISK DRIVER (PPIDE.ASM)

PPIDETRACE	.SET	3

all other default

**Comment by wwarthen** [comment] 2021-02-04 21:45
Hi Andrii,

Thanks for the boot messages and trying the TRACELEVEL change.  This does help me see what is going on.

First of all, the 8255 is being recognized by the CPU just fine.

Communication between the 8255 and the CF Card is marginal for some reason.  I can see some data exchange between the CF Card and the 8255, but it fails with a timeout in different places in the two different boots.  This is indicative of a poor connection between the 8255 and the CF Card.

I would suggest a thorough examination of the solder joints at the 8255 and the IDE connector.

If I understand correctly you have used the CF<->IDE adapter successfully in a different system, so that should be OK>

I suppose there is one other possibility.  You are using a 4314 motherboard.  This should be equivalent to my 2511, but I have never tested a 4314 and I don't know if anyone else has tried the PPIDE port of a 4314.  I suppose it is possible that there is a routing issue on the 4314.  However, that would typically result in a complete failure of the CF Card interface, whereas yours is "kind of" working.

I'm sorry I don't have any other suggestions.

Thanks,

Wayne

**Comment by AndriiKu** [comment] 2021-02-05 08:45
Hi Wayne,

I compare part of sheet  whis PPIDE on 2511 and 4314. And part where formed CS for PPI,
It's same.
Yes. It CF card and adapter work to Z180 Mark iV without any problem witj 3.0.1 BIOS. But there's no PPIDE.
Ok, I'll try check other CF card and may be ATA DISK MODULE from HP Thin PC, I use it to other project.

Thanks
Andrii

**Comment by wwarthen** [comment] 2021-02-05 22:29
It occurred to me to ask how you are powering the CF<->IDE adapter.  You are probably well aware of this, but it needs either a direct power connection or to be powered via pin 20 of the IDE interface (assuming the adapter supports power via pin 20).  If you are powering it through IDE pin 20, you need to short a jumper.  This is jumper K2 on the 2312.  Not sure about the 4314, but I would guess it is the same one.

-Wayne

**Comment by AndriiKu** [comment] 2021-02-06 07:50
I brainstormed. And rang all the tracks around the PPI and IDE connector.
I found output a PPI panel with cold solder. This is the pin of 12 - PC5.
My stupid mistake cost me many hours of tests. I'm sorry to bother you. 
Now everything works perfectly.

RomWBW HBIOS v3.1.1-pre.40, 2021-02-06

N8 Z8S180-N @ 18.432MHz IO=0x40
0 MEM W/S, 2 I/O W/S, INT MODE 2, MMU=N8
512KB ROM, 1024KB RAM

AY: IO=0x9C
ASCI0: IO=0x40 ASCI W/BRG MODE=38400,8,N,1
ASCI1: IO=0x41 ASCI W/BRG MODE=38400,8,N,1
DSRTC: MODE=STD IO=0x88 Sat 2021-02-06 09:50:31 CHARGE=ON
TMS: IO=0x98
PPK: IO=0x84
MD: UNITS=2 ROMDISK=384KB RAMDISK=768KB
FD: IO=0x8C UNITS=2
PPIDE: IO=0x80
PPIDE0: LBA BLOCKS=0x003D8000 SIZE=1968MB
PPIDE1: NO MEDIA
SD: MODE=CSIO OPR=0x88 CNTR=0x4A TRDR=0x4B DEVICES=1
SD0: SDSC NAME=SU128 BLOCKS=0x0003C100 SIZE=120MB

*** Activating CRT Console ***


Thank you all very much for your help. 

Good luck. 
Andrii

**Comment by wwarthen** [comment] 2021-02-06 16:50
Yeah, the old cold solder joint issue.  That will do it every time.

Very glad you got it working!  I will close this issue now.

Thanks,

Wayne

**Closed by wwarthen** 2021-02-06 16:50 UTC

**Comment by wrljet** [comment] 2021-02-06 22:42
I had an Ampro Little Board Z-80 that took me 25 years to get working, because of a defective IC socket.

**Comment by wwarthen** [comment] 2021-02-07 16:45
> I had an Ampro Little Board Z-80 that took me 25 years to get working, because of a defective IC socket.

OK, so that is a whole new definition for perseverance!

**Comment by wrljet** [comment] 2021-02-07 18:36
LOL!  Well, when I assembled the kit in 1983 or so, it didn't work, and I was unable to figure it out.

Years later during a burst of nostalgia I dragged it out and found the bad socket in an afternoon.

Bill
