### ISSUE TITLE
3.1.1 UNA_std.rom fails on Mark IV

### ISSUE THREAD

**Issue by sparky62** [wwarthen/RomWBW#291] opened 2022-06-26 10:44 UTC
Dunno if you welcome issues with the 3.1.1 pre-release but I tried UNA on Mark IV and got the following error when booting CP/M from the ROM:-

Welcome to Single Board Computing on the N8VEM SBC Z180 Mark IV
  running on a Z180 SL1960 retard processor
  with 512K of RAM and 512K of ROM
UNA BIOS version 2.1-45 of 14-Jan-2017.                             (13)

Copyright (C) 2013-2017 John R. Coffman.  All rights reserved.
Provided for hobbyist use on the RetroBrew Z80/Z180 boards.  This code may be
used under the terms of the GNU General Public License version 3, a copy of
which is contained in the file COPYING in the top-level source directory.

Do you wish to enter SETUP? [N/y]: 
Configuring the Z180 SBC Mark IV board:
Oscillator:  18.432 Mhz   Clock PHI:  18.432 Mhz   Effective:  10.24 Mhz

0: RAM-  RAMdrive on the Z180 SBC Mark IV board
LBASupported    UserAddressableSectors 832

1: ROM-  ROMdrive on the Z180 SBC Mark IV board
LBASupported    UserAddressableSectors 768

2:  SD-  SD  SS32G
s/n:          -719741752   fmw:  8.0   d/c:  2021-05
LBASupported    UserAddressableSectors 62333952

Boot UNA unit number or ROM? [R,X,0..2] (R): r

UNA Boot Loader

Boot [H=Help]: c

Loading CP/M 2.2...

CBIOS v3.1.1-pre.174 [UNA]

Configuring Drives...

        A:=RAM0:0
        B:=ROM1:0
        C:=SD2:0
        D:=SD2:1
        E:=SD2:2
        F:=SD2:3
        G:=SD2:4
        H:=SD2:5
        I:=SD2:6
        J:=SD2:7

        1363 Disk Buffer Bytes Free

CP/M-80 v2.2, 54.0K TPA

Bdos Err On A: Bad Sector

**Comment by wwarthen** [comment] 2022-06-26 14:20
I do welcome issues related to UNA.  I'm afraid that UNA is not regularly tested in the dev branch.  I will take a look at this.

Thanks,

Wayne

**Comment by wwarthen** [comment] 2022-06-27 00:14
Commit b82ff32 should correct basic UNA functionality.  I am going to close this issue, but let me know if the issue is not fixed for you and I will reopen it.

N.B., a full regression test of UNA in the dev branch is needed, but has **not** yet been completed.  Feel free to report additional UNA issues here.

Thanks,

Wayne

**Closed by wwarthen** 2022-06-27 00:14 UTC
Labels: bug
