### ISSUE TITLE
DDT vs. DDTZ vs. DDTZ80

### ISSUE THREAD

**Issue by Beatlor** [wwarthen/RomWBW#156] opened 2020-10-25 15:07 UTC
Hello everyone

I'm searching in the latest version of ROMWBW for a Z80 DDT version and found four different versions.
ddt.com ddtz.com ddtz27.com and final in MD0: ddtz80.com. The last one is this one with all the Z80
mnemonics (Assemble)  but I'm confused about a lot of ddtz.com version in the source folder but all aren't with Z80 menmonics. I thought ddtz.com is the one with the Z80 assemble and disassemble code.

**Comment by wwarthen** [comment] 2020-10-25 16:15
Odd.  The only variants of DDT that you should find within RomWBW are DDT.COM and DDTZ.COM.  DDT.COM is the original DRI issued debugger which is strictly based on 8080 mnemonics.  DDTZ is the the DDT-like implementation of DDT that understands Z80 mnemonics.  DDTZ.COM was developed independently by C.B. Falconer.

I am not sure where DDTZ27.COM and DDTZ80.COM came from.  They sound like name variations of DDTZ.COM.  What version of RomWBW are you using?  Perhaps an old version of RomWBW used those names.

Thanks,

Wayne

**Comment by Beatlor** [comment] 2020-10-25 16:41
Hi Wayne, yes that how I understood the differences between ddt.com and ddtz.com but when I start the ddtz.com. Found this here in the latest release 3.0.1 and as far as I remember I didn't see this issue in the 2.9.1 version.

B>ddtz
DDTZ v2.7M by CB Falconer. CPU=Z80
-l
?
-l100
?
-a 100
0100   ld a,0
?
0100   mvi a,0
0102

no "l" command nor understanding Z80 mnemonic but 8080th.

With the ddtz80:

A>ddtz80
DDT/Z   [8101]
> l
0100  NOP
0101  NOP
0102  NOP
0103  NOP
0104  NOP
0105  NOP
0106  NOP
0107  NOP
0108  NOP
0109  NOP
010A  NOP
010B  NOP
010C  NOP
010D  NOP
010E  NOP
010F  NOP
>>a 100
0100  NOP              ld a,0

> l100
0100  LD   A,00
0102  NOP

Correct assembled.

Also missing the > greater or >> sign as prompt in the native ddtz.com.

Thanks for your support.
Stephan

**Comment by wwarthen** [comment] 2020-10-25 20:21
As far as I can tell, DDTZ (which is the same as DDTZ27) is operating as intended.  It is a bit strange, but it seems to intentionally assemble and disassemble using 8080 mnemonics where possible and only uses Z80 mnemonics when there is no corresponding 8080 mnemonic.  The documentation eludes to this when it says:

> All  Z80-specific instructions can be (dis)assembled,  though in Intel rather  then Zilog format.

DDT, of course, is the DRI debugger that is only aware of 8080 mnemonics.

After a little searching, I found DDTZ80 on the Obsolescence Guaranteed Demo Disk contents.  It does indeed assemble and unassemble Zilog mnemonics.  The documentation file is in German, so I am not clear on it's heritage.  I don't think I have ever included this program on RomWBW disk contents.  Note that debuggers typically use RST 7 for single stepping which is incompatible with Z80 mode 1 interrupts.  So, I patch the included RomWBW debuggers to use RST 6.  I have no idea if DDTZ80 would use RST 7 for single stepping, but if so, it will have a problem running on RomWBW systems using mode 1 interrupts.

RomWBW does include ZSID from DRI.  This debugger does assemble/disassemble Zilog mnemonics.

If you think I have any of this wrong, please let me know.

Thanks,

Wayne

**Comment by Beatlor** [comment] 2020-10-26 18:31
ZSID is also a good option for for programming in Z80 mnemonics. Thanks for the tip.

BTW I found the ddtz80.com on the compiled ROM MD1:0

A: AMAZING  BAS : AMAZING  BBC : ART      TXT : BBCBASIC COM
A: COPY     CFG : COPY     COM : DDTZ27   COM : DDTZ80   COM
A: DDTZ80   DOC : DEBUGZ   COM : DEBUGZ   HLP : LDDS     COM
A: MBASIC   COM : POWER8   COM : SA       PAS : SENO     BAS
A: SENO     BBC : STARTREK BAS : STAT     COM : SURVEY   COM
A: TD       COM : TREKINST BAS : TURBO    COM : TURBO    MSG
A: TURBO    OVR : Z80ASM   COM : ZAP      COM

but also can't find it in the sources. After start the ddtz80 moves itself up in a higer memory area and wipes the main space from 0100-???? with zeros. You're right the ddtz80.doc is written in German. Whoever wrote this, no reference no author.

Think tonight will look into the boot menu for U(ser) - how and where I can put my code inside. 

Thanks for your support.

**Comment by wwarthen** [comment] 2020-10-27 02:09
Ok Stephan.  It seems like we are in sync now.  I don't think there is any further action required on this GitHub issue, so I will close it tomorrow if I don't hear anything else.

Thanks for raising this issue.  I learned a few things in the process.

Wayne

**Comment by wwarthen** [comment] 2020-10-27 20:43
I assume this is issue is resolved.  If not, please just open a new issue.

Thanks,

Wayne

**Closed by wwarthen** 2020-10-27 20:43 UTC
Labels: question
