### ISSUE TITLE
tasm not found when building dev under windows

### ISSUE THREAD

**Issue by vipoo** [wwarthen/RomWBW#281] opened 2022-02-05 06:18 UTC
Hi Wayne,

I just did a pull of the latest code today, and attempt to compile - (under dos/windows):
```
cd Source
Clean.bat
BuildShared.bat
etc
```

but I cant get `BuildShared` to work.  I get an error regarding tasm.  I tried adding Source\Tools\tasm32 to the path - but that did not seem to work.

```
        7 file(s) copied.
'tasm' is not recognized as an internal or external command,
operable program or batch file.
```

when i add tasm to the path (Tools\tasm32\), I get:

```
tasm: table file open error on ../../../../Tools\tasm32/tasm180.tab
```

Any idea what I need to do?

(Master branch builds fine)

Cheers
Dean

**Comment by wwarthen** [comment] 2022-02-05 15:36
On Fri, Feb 4, 2022 at 10:18 PM Dean Netherton ***@***.***>
wrote:

> I just did a pull of the latest code today, and attempt to compile -
> (under dos/windows):
>
> cd Source
> Clean.bat
> BuildShared.bat
> etc
>
> but I cant get BuildShared to work. I get an error regarding tasm. I
> tried adding Source\Tools\tasm32 to the path - but that did not seem to
> work.
>
>         7 file(s) copied.
> 'tasm' is not recognized as an internal or external command,
> operable program or batch file.
>
>
Hmmm... I do test builds on every check-in, but I suspect my environment is
allowing my build to work.  I will try the build in a "virgin"
environment.  I'm sure it is an easy fix and I will take care of it in a
few hours.  Thank you for bringing it to my attention.

-Wayne

**Comment by vipoo** [comment] 2022-02-05 20:56
Thanks Wayne,

Anything i can do to help.

**Comment by wwarthen** [comment] 2022-02-05 21:25
OK, this was a trivial fix (as expected).  Should be fine now (commit 214ed545843b964cda4945f5919aa95ac5b3b06a).  I will leave this issue open until you can confirm it is working for you.

Thanks,

Wayne

**Comment by vipoo** [comment] 2022-02-06 00:21
Hi Wayne,

Thanks - just did a check - all works well now - thanks for that.

It allowed me to test my TurboCPU module, as per the discussion on the google groups.

I found that SIO/2 interrupt handling now works nicely, if I just add the following code inside the common int handler:

```
#IFDEF MSX_TURBO_CPU
	OUT	(MSX_TURBO_CPU), A
#ENDIF
	RETI				; AND RETURN
```

And for my config, I just add:

`#DEFINE MSX_TURBO_CPU	$FF`  Just need a random non-used IO port address to trigger the clock sync mode of the TurboCPU module.


This is a bit of a niche scenario - not sure if you want to have this in the code?  Happy to forward a merge commit if you like - but also totally understand if you prefer not to have this - as I do feel its a little niche...

Cheers
Dean

**Comment by wwarthen** [comment] 2022-02-06 00:28
> Thanks - just did a check - all works well now - thanks for that.

Excellent.  I will close this issue now.
 
> It allowed me to test my TurboCPU module, as per the discussion on the google groups.
> 
> I found that SIO/2 interrupt handling now works nicely, if I just add the following code inside the common int handler:
> 
> ```
> #IFDEF MSX_TURBO_CPU
> 	OUT	(MSX_TURBO_CPU), A
> #ENDIF
> 	RETI				; AND RETURN
> ```
> 
> And for my config, I just add:
> 
> `#DEFINE MSX_TURBO_CPU $FF` Just need a random non-used IO port address to trigger the clock sync mode of the TurboCPU module.
> 
> This is a bit of a niche scenario - not sure if you want to have this in the code? Happy to forward a merge commit if you like - but also totally understand if you prefer not to have this - as I do feel its a little niche...

I'm happy to include this since it has minimal code impact.  I will just warn you that I will not be regression testing this going forward.  I don't think I am likely to break this, but no guarantees.  Feel free to send a PR at your convenience.

It is interesting how you fixed the problem.  Does the speed stay "slow" for a bit after the I/O instruction completes?

Thanks,

Wayne

**Closed by wwarthen** 2022-02-06 00:28 UTC

**Comment by vipoo** [comment] 2022-02-06 00:31
Thanks Wayne - and yep - I would not expect you to continue to test this... But I think the risk is low that it breaks.

And yes, the speed stays slow for 32 clock cycles - this was the amount I needed to achieve compatibility with the V9958 chip.  Anything less and existing MSX software has a chance of sending commands too fast to the video chip.

I will get a PR organise shortly - thanks.

Cheers
Dean
